import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Fonts:
import { fontSans, instrumentSans } from "@/fonts";

// Providers:
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/themeProvider";

// Metadata:
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            `${fontSans.variable} ${instrumentSans.variable}`,
            "font-sans antialiased",
            "bg-zinc-100 text-zinc-900 dark:bg-zinc-900 dark:text-zinc-50",
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
