import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Fonts:
import { fontSans } from "@/fonts";

// Metadata:
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" className={cn(`${fontSans.variable}`)}>
      <body>{children}</body>
    </html>
  );
}
